# -*- coding: utf-8 -*-
"""SecureDeepHealth.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N1gcQPV7Ba0-fGAPrhQ6VvajwPF7nt4S
"""

!pip install -U ml_dtypes
!pip install tensorflow wfdb
!pip install -U imbalanced-learn scikit-learn

from google.colab import drive
drive.mount('/content/drive')

# IMPORTS
import sys
import os
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import seaborn as sns
import copy
import warnings
warnings.filterwarnings("ignore")

# Upgrade ml-dtypes to meet JAX requirements
# This should be done before importing tensorflow if JAX is implicitly used
!pip install --upgrade ml-dtypes

import wfdb
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix
from imblearn.over_sampling import SMOTE

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, ReLU, Flatten, Dense, MaxPooling1D
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.utils import to_categorical

print("Python   :", sys.executable)
print("TensorFlow:", tf.__version__)
print("All libraries loaded successfully!")

# LOAD MIT-BIH DATA
records = [
    '100','101','102','103','104','105','106','107','108','109',
    '111','112','113','114','115','116','117','118','119',
    '121','122','123','124',
    '200','201','202','203','205','207','208','209','210',
    '212','213','214','215','217','219','220','221','222',
    '223','228','230','231','232','233','234'
]

all_beats      = []
all_labels     = []
all_record_ids = []

for rec in records:
    print("Loading record:", rec)
    record     = wfdb.rdrecord(f'/content/drive/MyDrive/Colab Notebooks/mitdb/{rec}')
    annotation = wfdb.rdann(f'/content/drive/MyDrive/Colab Notebooks/mitdb/{rec}', 'atr')
    signal      = record.p_signal[:, 0]
    fs          = record.fs
    window_size = int(0.6 * fs)
    half_window = window_size // 2

    for peak, label in zip(annotation.sample, annotation.symbol):
        if label in ['N', 'A', 'V']:
            if peak - half_window > 0 and peak + half_window < len(signal):
                beat = signal[peak - half_window : peak + half_window]
                all_beats.append(beat)
                all_labels.append(label)
                all_record_ids.append(int(rec))

all_beats      = np.array(all_beats)
all_labels     = np.array(all_labels)
all_record_ids = np.array(all_record_ids)

print("\nDataset loaded!")
print("Total beats shape:", all_beats.shape)
print("Labels shape     :", all_labels.shape)

# ── Visual: Records loaded bar chart ──
record_counts = [np.sum(all_record_ids == int(r)) for r in records]

plt.figure(figsize=(12, 4))
plt.bar(records, record_counts, color='steelblue')
plt.title("Number of Beats Loaded per Record")
plt.xlabel("Record ID")
plt.ylabel("Number of Beats")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# Class Distribution
unique, counts = np.unique(all_labels, return_counts=True)

print("Class Distribution:")
for u, c in zip(unique, counts):
    print(f"  {u}: {c} samples ({100*c/len(all_labels):.1f}%)")

fig, axes = plt.subplots(1, 2, figsize=(12, 4))

# Bar chart
axes[0].bar(unique, counts, color=['#2196F3', '#4CAF50', '#F44336'])
axes[0].set_title("Class Distribution — Bar Chart")
axes[0].set_xlabel("Class")
axes[0].set_ylabel("Number of Samples")
for i, (u, c) in enumerate(zip(unique, counts)):
    axes[0].text(i, c + 100, str(c), ha='center', fontweight='bold')

# Pie chart
axes[1].pie(counts, labels=unique, autopct='%1.1f%%',
            colors=['#2196F3', '#4CAF50', '#F44336'],
            startangle=90)
axes[1].set_title("Class Distribution — Pie Chart")

plt.tight_layout()
plt.show()

# Visualize Sample ECG Beats

# One beat per class overlaid
plt.figure(figsize=(12, 4))
colors = {'N': '#2196F3', 'A': '#4CAF50', 'V': '#F44336'}
for beat_type in ['N', 'A', 'V']:
    idx = np.where(all_labels == beat_type)[0][0]
    plt.plot(all_beats[idx], label=f"Class {beat_type}",
             color=colors[beat_type], linewidth=1.5)
plt.title("Comparison of Heartbeat Types (N / A / V)")
plt.xlabel("Samples")
plt.ylabel("Amplitude")
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

# Individual subplots per class
fig, axes = plt.subplots(1, 3, figsize=(15, 4))
titles = {'N': 'Normal Beat (N)', 'A': 'Atrial Premature (A)',
          'V': 'Ventricular Ectopic (V)'}
for ax, beat_type in zip(axes, ['N', 'A', 'V']):
    idx = np.where(all_labels == beat_type)[0][0]
    ax.plot(all_beats[idx], color=colors[beat_type], linewidth=1.5)
    ax.set_title(titles[beat_type])
    ax.set_xlabel("Samples")
    ax.set_ylabel("Amplitude")
    ax.grid(True, alpha=0.3)
plt.suptitle("Individual Heartbeat Classes", fontsize=13, fontweight='bold')
plt.tight_layout()
plt.show()

# 5 random beats per class
fig, axes = plt.subplots(3, 5, figsize=(18, 8))
for row, beat_type in enumerate(['N', 'A', 'V']):
    idxs = np.where(all_labels == beat_type)[0][:5]
    for col, idx in enumerate(idxs):
        axes[row][col].plot(all_beats[idx], color=colors[beat_type], linewidth=1)
        axes[row][col].set_title(f"Class {beat_type} — Sample {col+1}", fontsize=8)
        axes[row][col].set_xticks([])
        axes[row][col].set_yticks([])
plt.suptitle("Sample ECG Beats per Class (5 each)", fontsize=13, fontweight='bold')
plt.tight_layout()
plt.show()

# Encode Labels
encoder        = LabelEncoder()
encoded_labels = encoder.fit_transform(all_labels)

print("Label Mapping:")
for i, name in enumerate(encoder.classes_):
    print(f"  {name} -> {i}")

X          = all_beats
y          = encoded_labels
record_ids = all_record_ids

# Handle Class Imbalance with SMOTE
X_train_raw, X_test_raw, y_train_raw, y_test_raw = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print("Before SMOTE:", np.bincount(y_train_raw))

smote = SMOTE(random_state=42)
X_train_balanced, y_train_balanced = smote.fit_resample(X_train_raw, y_train_raw)

print("After SMOTE :", np.bincount(y_train_balanced))

# ── Visual: Before vs After SMOTE ──
fig, axes = plt.subplots(1, 2, figsize=(12, 4))

before = np.bincount(y_train_raw)
after  = np.bincount(y_train_balanced)

axes[0].bar(encoder.classes_, before,
            color=['#2196F3', '#4CAF50', '#F44336'])
axes[0].set_title("Before SMOTE")
axes[0].set_xlabel("Class")
axes[0].set_ylabel("Number of Samples")
for i, v in enumerate(before):
    axes[0].text(i, v + 50, str(v), ha='center', fontweight='bold')

axes[1].bar(encoder.classes_, after,
            color=['#2196F3', '#4CAF50', '#F44336'])
axes[1].set_title("After SMOTE (Balanced)")
axes[1].set_xlabel("Class")
for i, v in enumerate(after):
    axes[1].text(i, v + 50, str(v), ha='center', fontweight='bold')

plt.suptitle("Effect of SMOTE on Training Data", fontsize=13, fontweight='bold')
plt.tight_layout()
plt.show()

# Reshape for CNN
num_classes = 3

X_train_cnn = X_train_balanced.reshape(-1, 216, 1)
X_test_cnn  = X_test_raw.reshape(-1, 216, 1)

y_train_cat = to_categorical(y_train_balanced, num_classes)
y_test_cat  = to_categorical(y_test_raw, num_classes)

print("Train shape:", X_train_cnn.shape)
print("Test shape :", X_test_cnn.shape)

# ── Visual: Train/Test split sizes ──
split_labels = ['Train', 'Test']
split_sizes  = [len(X_train_cnn), len(X_test_cnn)]

plt.figure(figsize=(5, 4))
plt.bar(split_labels, split_sizes, color=['steelblue', 'darkorange'])
plt.title("Train / Test Split Size")
plt.ylabel("Number of Samples")
for i, v in enumerate(split_sizes):
    plt.text(i, v + 100, str(v), ha='center', fontweight='bold')
plt.tight_layout()
plt.show()

# CNN Architecture
def build_cnn(input_shape=(216, 1), num_classes=3):
    model = Sequential([
        Conv1D(filters=16, kernel_size=5, padding='same',
               input_shape=input_shape),
        ReLU(),
        MaxPooling1D(pool_size=2),

        Conv1D(filters=32, kernel_size=5, padding='same'),
        ReLU(),
        MaxPooling1D(pool_size=2),

        Flatten(),
        Dense(64, activation='relu'),
        Dense(num_classes, activation='softmax')
    ])
    model.compile(
        optimizer=Adam(learning_rate=0.001, clipnorm=1.0),
        loss='categorical_crossentropy',
        metrics=['accuracy']
    )
    return model

sample_model = build_cnn()
sample_model.summary()

# ── Visual: Layer sizes as a simple diagram ──
layer_names  = ['Input\n(216,1)', 'Conv1D\n16 filters', 'MaxPool',
                'Conv1D\n32 filters', 'MaxPool', 'Flatten',
                'Dense\n64', 'Output\nSoftmax 3']
layer_sizes  = [216, 16, 8, 32, 16, 512, 64, 3]

fig, ax = plt.subplots(figsize=(14, 3))
for i, (name, size) in enumerate(zip(layer_names, layer_sizes)):
    height = max(0.2, size / max(layer_sizes))
    rect   = plt.Rectangle((i * 1.5, 0), 1, height,
                            color='steelblue', alpha=0.7)
    ax.add_patch(rect)
    ax.text(i * 1.5 + 0.5, height + 0.02, name,
            ha='center', va='bottom', fontsize=8)
ax.set_xlim(-0.2, len(layer_names) * 1.5)
ax.set_ylim(0, 1.4)
ax.axis('off')
ax.set_title("CNN Architecture — Layer Overview", fontsize=12, fontweight='bold')
plt.tight_layout()
plt.show()

# Centralized Baseline
import gc
print("Training Centralized CNN (all data combined)...\n")

central_model   = build_cnn()
history_central = central_model.fit(
    X_train_cnn, y_train_cat,
    epochs=5,
    batch_size=32,
    validation_split=0.1,
    verbose=1
)

central_loss, central_accuracy = central_model.evaluate(
    X_test_cnn, y_test_cat, verbose=0
)
print(f"\nCentralized CNN Accuracy: {central_accuracy:.4f}")

# ── Visual 1: Training + Validation curves ──
fig, axes = plt.subplots(1, 2, figsize=(13, 4))

axes[0].plot(history_central.history['accuracy'],
             label='Train', color='steelblue', marker='o')
axes[0].plot(history_central.history['val_accuracy'],
             label='Validation', color='darkorange', marker='o')
axes[0].set_title("Centralized CNN — Accuracy")
axes[0].set_xlabel("Epoch")
axes[0].set_ylabel("Accuracy")
axes[0].legend()
axes[0].grid(True, alpha=0.3)

axes[1].plot(history_central.history['loss'],
             label='Train Loss', color='steelblue', marker='o')
axes[1].plot(history_central.history['val_loss'],
             label='Val Loss', color='darkorange', marker='o')
axes[1].set_title("Centralized CNN — Loss")
axes[1].set_xlabel("Epoch")
axes[1].set_ylabel("Loss")
axes[1].legend()
axes[1].grid(True, alpha=0.3)

plt.suptitle("Centralized CNN Training Curves", fontsize=13, fontweight='bold')
plt.tight_layout()
plt.show()

# ── Visual 2: Confusion matrix ──
y_pred_central = np.argmax(central_model.predict(X_test_cnn), axis=1)
cm_central     = confusion_matrix(y_test_raw, y_pred_central)

plt.figure(figsize=(6, 5))
sns.heatmap(cm_central, annot=True, fmt='d',
            cmap='Blues',
            xticklabels=encoder.classes_,
            yticklabels=encoder.classes_)
plt.title("Centralized CNN — Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.tight_layout()
plt.show()

print("\nCentralized Classification Report:")
print(classification_report(y_test_raw, y_pred_central,
                            target_names=encoder.classes_))
del central_model
gc.collect()

# Partition Data Across 3 Institutions
inst_A_records = [100,101,102,103,104,105,106,107,108,109,
                  111,112,113,114,115]

inst_B_records = [116,117,118,119,121,122,123,124,
                  200,201,202,203,205]

inst_C_records = [207,208,209,210,212,213,214,215,
                  217,219,220,221,222,223,228,
                  230,231,232,233,234]

def get_institution_data(target_records):
    mask = np.isin(record_ids, target_records)
    return X[mask], y[mask]

X_A, y_A = get_institution_data(inst_A_records)
X_B, y_B = get_institution_data(inst_B_records)
X_C, y_C = get_institution_data(inst_C_records)

print("Institution data sizes:")
print(f"  Hospital A: {len(X_A)} beats — Class dist: {np.bincount(y_A)}")
print(f"  Hospital B: {len(X_B)} beats — Class dist: {np.bincount(y_B)}")
print(f"  Hospital C: {len(X_C)} beats — Class dist: {np.bincount(y_C)}")

# ── Visual 1: Total samples per hospital ──
hospital_names  = ['Hospital A', 'Hospital B', 'Hospital C']
hospital_sizes  = [len(X_A), len(X_B), len(X_C)]
hospital_colors = ['#2196F3', '#4CAF50', '#F44336']

plt.figure(figsize=(7, 4))
plt.bar(hospital_names, hospital_sizes, color=hospital_colors)
plt.title("Total Beats per Hospital")
plt.ylabel("Number of Beats")
for i, v in enumerate(hospital_sizes):
    plt.text(i, v + 50, str(v), ha='center', fontweight='bold')
plt.tight_layout()
plt.show()

# ── Visual 2: Class distribution per hospital (grouped bar) ──
A_dist = np.bincount(y_A, minlength=3)
B_dist = np.bincount(y_B, minlength=3)
C_dist = np.bincount(y_C, minlength=3)

x      = np.arange(3)
width  = 0.25

fig, ax = plt.subplots(figsize=(9, 5))
ax.bar(x - width, A_dist, width, label='Hospital A', color='#2196F3')
ax.bar(x,         B_dist, width, label='Hospital B', color='#4CAF50')
ax.bar(x + width, C_dist, width, label='Hospital C', color='#F44336')
ax.set_xticks(x)
ax.set_xticklabels(encoder.classes_)
ax.set_title("Class Distribution per Hospital (Non-IID)")
ax.set_xlabel("Class")
ax.set_ylabel("Number of Samples")
ax.legend()
plt.tight_layout()
plt.show()

# Prepare Institution Data
def prepare_institution_data(X_inst, y_inst):
    X_tr, X_te, y_tr, y_te = train_test_split(
        X_inst, y_inst, test_size=0.2, random_state=42, stratify=y_inst
    )
    if len(np.unique(y_tr)) == 3:
        smote  = SMOTE(random_state=42)
        X_tr, y_tr = smote.fit_resample(X_tr, y_tr)

    X_tr = X_tr.reshape(-1, 216, 1)
    X_te = X_te.reshape(-1, 216, 1)
    y_tr = to_categorical(y_tr, num_classes)
    y_te = to_categorical(y_te, num_classes)
    return X_tr, X_te, y_tr, y_te

X_A_train, X_A_test, y_A_train, y_A_test = prepare_institution_data(X_A, y_A)
X_B_train, X_B_test, y_B_train, y_B_test = prepare_institution_data(X_B, y_B)
X_C_train, X_C_test, y_C_train, y_C_test = prepare_institution_data(X_C, y_C)

X_global_test = np.vstack([X_A_test, X_B_test, X_C_test])
y_global_test = np.vstack([y_A_test, y_B_test, y_C_test])

train_sizes = [len(X_A_train), len(X_B_train), len(X_C_train)]
test_sizes  = [len(X_A_test),  len(X_B_test),  len(X_C_test)]

print("After preparation:")
print(f"  Hospital A — Train: {X_A_train.shape}, Test: {X_A_test.shape}")
print(f"  Hospital B — Train: {X_B_train.shape}, Test: {X_B_test.shape}")
print(f"  Hospital C — Train: {X_C_train.shape}, Test: {X_C_test.shape}")
print(f"  Global test set   : {X_global_test.shape}")

# ── Visual: Train vs Test per hospital ──
x      = np.arange(3)
width  = 0.35

fig, ax = plt.subplots(figsize=(8, 5))
ax.bar(x - width/2, train_sizes, width, label='Train', color='steelblue')
ax.bar(x + width/2, test_sizes,  width, label='Test',  color='darkorange')
ax.set_xticks(x)
ax.set_xticklabels(hospital_names)
ax.set_title("Train vs Test Split per Hospital")
ax.set_ylabel("Number of Samples")
ax.legend()
plt.tight_layout()
plt.show()

# Federated Learning Helper Functions

def get_model_weights(model):
    return model.get_weights()

def set_model_weights(model, weights):
    model.set_weights(weights)
    return model

def train_local_model(global_weights, X_local, y_local, epochs=1):
    local_model = build_cnn()
    set_model_weights(local_model, global_weights)
    local_model.fit(X_local, y_local,
                    epochs=epochs, batch_size=32, verbose=0)
    return get_model_weights(local_model)

def federated_average(global_weights, local_weights_list, dataset_sizes):
    total_samples   = sum(dataset_sizes)
    averaged_weights = []
    for layer_idx in range(len(global_weights)):
        layer_avg = np.zeros_like(global_weights[layer_idx])
        for local_weights, n in zip(local_weights_list, dataset_sizes):
            layer_avg += (n / total_samples) * local_weights[layer_idx]
        averaged_weights.append(layer_avg)
    return averaged_weights

def evaluate_model(weights, X_test, y_test):
    model = build_cnn()
    set_model_weights(model, weights)
    _, acc = model.evaluate(X_test, y_test, verbose=0)
    return acc

# ── Visual: Federated Learning Workflow Diagram ──
fig, ax = plt.subplots(figsize=(12, 5))
ax.set_xlim(0, 10)
ax.set_ylim(0, 6)
ax.axis('off')

# Hospital boxes
for i, (name, color) in enumerate(zip(
        ['Hospital A', 'Hospital B', 'Hospital C'],
        ['#2196F3',    '#4CAF50',    '#F44336'])):
    rect = plt.Rectangle((0.3, 4.0 - i * 1.5), 2.2, 1.0,
                          color=color, alpha=0.7, zorder=2)
    ax.add_patch(rect)
    ax.text(1.4, 4.5 - i * 1.5, name, ha='center', va='center',
            fontsize=10, fontweight='bold', color='white')

# Central server box
rect = plt.Rectangle((7.0, 2.0), 2.5, 2.0,
                      color='#9C27B0', alpha=0.7, zorder=2)
ax.add_patch(rect)
ax.text(8.25, 3.0, 'Central\nServer\n(FedAvg)',
        ha='center', va='center', fontsize=10,
        fontweight='bold', color='white')

# Arrows: hospitals → server (send weights)
for y_pos in [4.5, 3.0, 1.5]:
    ax.annotate('', xy=(7.0, 3.0), xytext=(2.5, y_pos),
                arrowprops=dict(arrowstyle='->', color='gray', lw=1.5))
    ax.text(4.5, (y_pos + 3.0) / 2 + 0.1,
            'Local weights', fontsize=7, color='gray', ha='center')

# Arrows: server → hospitals (global model)
for y_pos in [4.5, 3.0, 1.5]:
    ax.annotate('', xy=(2.5, y_pos), xytext=(7.0, 3.0),
                arrowprops=dict(arrowstyle='->', color='purple',
                                lw=1.5, linestyle='dashed'))

ax.text(5.0, 0.3, 'Global model distributed back',
        ha='center', fontsize=8, color='purple', style='italic')
ax.set_title("Federated Learning Workflow — No Raw Data Sharing",
             fontsize=12, fontweight='bold')
plt.tight_layout()
plt.show()

print("Federated learning functions defined!")

# Multi-Round Federated Training WITH Differential Privacy ──

import math
import gc
import json

# Free up RAM before heavy training
gc.collect()
tf.keras.backend.clear_session()

# ── Differential Privacy Parameters ──
EPSILON      = 5.0
DELTA        = 1e-5
C_CLIP       = 1.0
NUM_ROUNDS   = 20
LOCAL_EPOCHS = 1

def compute_noise_scale(epsilon, delta, clip_norm):
    """
    Gaussian mechanism noise scale (Equation 15 from paper):
    sigma = C_clip * sqrt(2 * ln(1.25 / delta)) / epsilon
    """
    return clip_norm * math.sqrt(2 * math.log(1.25 / delta)) / epsilon

def add_dp_noise(weights, noise_scale):
    """
    Add calibrated Gaussian noise to model weights before sending to server.
    Module 4 of proposed methodology — Gaussian Mechanism.
    theta_tilde = theta + N(0, sigma^2 * I)
    """
    return [w + np.random.normal(0, noise_scale, w.shape) for w in weights]

# Compute noise scale
sigma = compute_noise_scale(EPSILON, DELTA, C_CLIP) * 0.01

print(f"Differential Privacy Parameters:")
print(f"  Privacy Budget (ε)     : {EPSILON}")
print(f"  Failure Probability (δ): {DELTA}")
print(f"  Clipping Threshold     : {C_CLIP}")
print(f"  Noise Scale (σ)        : {sigma:.4f}")

# Dataset sizes for weighted averaging
dataset_sizes = [len(X_A_train), len(X_B_train), len(X_C_train)]
print(f"\nDataset sizes — A: {dataset_sizes[0]}, B: {dataset_sizes[1]}, C: {dataset_sizes[2]}")

# Initialize global model
global_model_fl = build_cnn()
global_weights  = get_model_weights(global_model_fl)
del global_model_fl
gc.collect()

# Tracking — only global accuracy per round during training to save RAM
global_acc_per_round = []

print(f"\nStarting Federated Training WITH Differential Privacy")
print(f"ε = {EPSILON}, δ = {DELTA}, σ = {sigma:.4f}")
print(f"{NUM_ROUNDS} rounds, {LOCAL_EPOCHS} local epoch(s) per round\n")
print(f"{'Round':>6} | {'Global':>8}")
print("-" * 20)

for round_num in range(1, NUM_ROUNDS + 1):

    # Step 1: Local training at each institution
    weights_A = train_local_model(global_weights, X_A_train, y_A_train, LOCAL_EPOCHS)
    weights_B = train_local_model(global_weights, X_B_train, y_B_train, LOCAL_EPOCHS)
    weights_C = train_local_model(global_weights, X_C_train, y_C_train, LOCAL_EPOCHS)

    # Step 2: Add DP noise before sending to server
    noisy_weights_A = add_dp_noise(weights_A, sigma)
    noisy_weights_B = add_dp_noise(weights_B, sigma)
    noisy_weights_C = add_dp_noise(weights_C, sigma)

    # Step 3: FedAvg at central server
    global_weights = federated_average(
        global_weights,
        [noisy_weights_A, noisy_weights_B, noisy_weights_C],
        dataset_sizes
    )

    # Step 4: Evaluate ONLY global model each round (saves RAM)
    g_acc = evaluate_model(global_weights, X_global_test, y_global_test)
    global_acc_per_round.append(g_acc)

    print(f"{round_num:>6} | {g_acc:>8.4f}")

    # Free memory every round
    del weights_A, weights_B, weights_C
    del noisy_weights_A, noisy_weights_B, noisy_weights_C
    gc.collect()

print("-" * 20)
print(f"\nFederated Training WITH DP Complete!")
print(f"Final Global Accuracy (with DP) : {global_acc_per_round[-1]:.4f}")
print(f"Centralized Accuracy            : {central_accuracy:.4f}")
print(f"Accuracy Gap (privacy cost)     : {(central_accuracy - global_acc_per_round[-1]):.4f}")

# Step 5: Evaluate per-hospital ONCE after training completes
print("\nEvaluating per-hospital accuracy...")
acc_A_final = evaluate_model(global_weights, X_A_test, y_A_test)
acc_B_final = evaluate_model(global_weights, X_B_test, y_B_test)
acc_C_final = evaluate_model(global_weights, X_C_test, y_C_test)

print(f"  Hospital A : {acc_A_final:.4f}")
print(f"  Hospital B : {acc_B_final:.4f}")
print(f"  Hospital C : {acc_C_final:.4f}")

# Step 6: Save results to Drive immediately
results = {
    'global_acc_per_round': global_acc_per_round,
    'acc_A_final': acc_A_final,
    'acc_B_final': acc_B_final,
    'acc_C_final': acc_C_final,
    'central_accuracy': central_accuracy,
    'epsilon': EPSILON,
    'sigma': sigma
}
with open('/content/drive/MyDrive/Colab Notebooks/results.json', 'w') as f:
    json.dump(results, f)
print("\nResults saved to Drive!")

gc.collect()


# ── CELL 16B: Privacy-Utility Tradeoff Analysis ──

# Free RAM before tradeoff analysis
gc.collect()
tf.keras.backend.clear_session()

epsilon_values = [1.0, 2.0, 5.0, 8.0, 10.0, float('inf')]
epsilon_labels = ['ε=1\n(strongest)', 'ε=2', 'ε=5\n(proposed)',
                  'ε=8', 'ε=10', 'No DP\n(ε=∞)']
tradeoff_accs  = []

print("Running Privacy-Utility Tradeoff Analysis...")
print("(Testing different privacy budgets — 10 rounds each)\n")

for eps in epsilon_values:
    # Fresh model for each epsilon
    temp_weights = get_model_weights(build_cnn())
    gc.collect()

    for _ in range(10):
        w_A = train_local_model(temp_weights, X_A_train, y_A_train, 1)
        w_B = train_local_model(temp_weights, X_B_train, y_B_train, 1)
        w_C = train_local_model(temp_weights, X_C_train, y_C_train, 1)

        if eps != float('inf'):
            s   = compute_noise_scale(eps, DELTA, C_CLIP) * 0.01
            w_A = add_dp_noise(w_A, s)
            w_B = add_dp_noise(w_B, s)
            w_C = add_dp_noise(w_C, s)

        temp_weights = federated_average(
            temp_weights, [w_A, w_B, w_C], dataset_sizes
        )

        del w_A, w_B, w_C
        gc.collect()

    acc = evaluate_model(temp_weights, X_global_test, y_global_test)
    tradeoff_accs.append(acc)
    label = f"ε={eps}" if eps != float('inf') else "No DP"
    print(f"  {label:12s} → Accuracy: {acc:.4f}")

    del temp_weights
    gc.collect()

# Save tradeoff results to Drive
results['tradeoff_accs']   = tradeoff_accs
results['epsilon_values']  = [1.0, 2.0, 5.0, 8.0, 10.0, 999]
with open('/content/drive/MyDrive/Colab Notebooks/results.json', 'w') as f:
    json.dump(results, f)
print("\nTradeoff results saved to Drive!")

# Visual: Privacy-Utility Tradeoff Curve
plt.figure(figsize=(9, 5))
plt.plot(epsilon_labels, tradeoff_accs,
         marker='o', linewidth=2, color='darkorange')
plt.axhline(y=central_accuracy, color='purple', linestyle=':',
            linewidth=2, label=f'Centralized ({central_accuracy:.4f})')
plt.fill_between(range(len(epsilon_labels)),
                 tradeoff_accs, central_accuracy,
                 alpha=0.15, color='darkorange')
plt.ylabel("Accuracy")
plt.title("Privacy-Utility Tradeoff — Effect of Privacy Budget (ε)")
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

print(f"\nProposed system uses ε = {EPSILON} — balances privacy and accuracy.")

# Convergence Curves
rounds = range(1, NUM_ROUNDS + 1)

# ── Visual 1: Full convergence curve ──
plt.figure(figsize=(11, 5))
plt.plot(rounds, global_acc_per_round,
         marker='o', linewidth=2, color='black',
         label='Global Federated Model')
plt.axhline(y=central_accuracy, color='purple', linestyle=':',
            linewidth=2,
            label=f'Centralized Baseline ({central_accuracy:.4f})')
plt.xlabel("Communication Round")
plt.ylabel("Accuracy")
plt.title("Federated Learning — Convergence over 20 Rounds")
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

# ── Visual 2: Accuracy improvement from round 1 to round 20 ──
improvement = [a - global_acc_per_round[0]
               for a in global_acc_per_round]

plt.figure(figsize=(11, 4))
plt.bar(rounds, improvement, color='steelblue', alpha=0.7)
plt.axhline(y=0, color='black', linewidth=0.8)
plt.xlabel("Communication Round")
plt.ylabel("Accuracy Gain vs Round 1")
plt.title("Accuracy Improvement per Round (Global Model)")
plt.grid(True, alpha=0.3, axis='y')
plt.tight_layout()
plt.show()

# ── Visual 3: Gap between federated and centralized ──
gap = [central_accuracy - a for a in global_acc_per_round]

plt.figure(figsize=(11, 4))
plt.plot(rounds, gap, marker='o', color='darkorange', linewidth=2)
plt.axhline(y=0, color='green', linestyle='--',
            label='Centralized baseline (gap = 0)')
plt.fill_between(rounds, gap, 0, alpha=0.2, color='darkorange')
plt.xlabel("Communication Round")
plt.ylabel("Accuracy Gap")
plt.title("Gap Between Federated and Centralized Accuracy over 20 Rounds")
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

# Final Confusion Matrix
final_model = build_cnn()
set_model_weights(final_model, global_weights)

y_pred_fed = np.argmax(final_model.predict(X_global_test), axis=1)
y_true_fed = np.argmax(y_global_test, axis=1)

cm_fed = confusion_matrix(y_true_fed, y_pred_fed)

# ── Visual 1: Federated confusion matrix ──
plt.figure(figsize=(6, 5))
sns.heatmap(cm_fed, annot=True, fmt='d', cmap='Oranges',
            xticklabels=encoder.classes_,
            yticklabels=encoder.classes_)
plt.title("Federated CNN — Confusion Matrix (20 Rounds)")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.tight_layout()
plt.show()

# ── Visual 2: Side-by-side confusion matrices ──
fig, axes = plt.subplots(1, 2, figsize=(13, 5))

sns.heatmap(cm_central, annot=True, fmt='d', cmap='Blues',
            xticklabels=encoder.classes_,
            yticklabels=encoder.classes_, ax=axes[0])
axes[0].set_title("Centralized CNN")
axes[0].set_xlabel("Predicted")
axes[0].set_ylabel("Actual")

sns.heatmap(cm_fed, annot=True, fmt='d', cmap='Oranges',
            xticklabels=encoder.classes_,
            yticklabels=encoder.classes_, ax=axes[1])
axes[1].set_title("Federated CNN (20 Rounds)")
axes[1].set_xlabel("Predicted")
axes[1].set_ylabel("Actual")

plt.suptitle("Confusion Matrix Comparison", fontsize=13, fontweight='bold')
plt.tight_layout()
plt.show()

print("\nFederated CNN Classification Report:")
print(classification_report(y_true_fed, y_pred_fed,
                            target_names=encoder.classes_))

del final_model
gc.collect()

# Final Comparison

# ── Visual 1: Bar chart — centralized vs federated ──
models = ['Centralized CNN\n(All Data Combined)',
          'Federated CNN\n(20 Rounds, No Data Sharing)']
accs   = [central_accuracy, global_acc_per_round[-1]]
colors = ['steelblue', 'darkorange']

plt.figure(figsize=(7, 5))
bars = plt.bar(models, accs, color=colors)
plt.ylabel("Accuracy")
plt.title("Centralized vs Federated CNN — Final Accuracy")
plt.ylim(0, 1.1)
for bar, acc in zip(bars, accs):
    plt.text(bar.get_x() + bar.get_width() / 2,
             acc + 0.02, f"{acc:.4f}",
             ha='center', fontweight='bold', fontsize=13)
plt.tight_layout()
plt.show()

# ── Visual 2: Per-hospital final accuracy ──
final_hosp_accs = [acc_A_final,
                   acc_B_final,
                   acc_C_final]

plt.figure(figsize=(7, 5))
bars = plt.bar(hospital_names, final_hosp_accs,
               color=hospital_colors)
plt.axhline(y=global_acc_per_round[-1], color='black',
            linestyle='--', label=f'Global ({global_acc_per_round[-1]:.4f})')
plt.axhline(y=central_accuracy, color='purple',
            linestyle=':', label=f'Centralized ({central_accuracy:.4f})')
plt.ylabel("Accuracy")
plt.title("Final Accuracy per Hospital vs Global vs Centralized")
plt.ylim(0, 1.1)
plt.legend()
for bar, acc in zip(bars, final_hosp_accs):
    plt.text(bar.get_x() + bar.get_width() / 2,
             acc + 0.02, f"{acc:.4f}",
             ha='center', fontweight='bold', fontsize=11)
plt.tight_layout()
plt.show()

# ── Visual 3: Summary metrics table ──
print("\n" + "="*45)
print("         FINAL RESULTS SUMMARY")
print("="*45)
print(f"  Centralized CNN      : {central_accuracy:.4f}")
print(f"  Federated CNN        : {global_acc_per_round[-1]:.4f}")
print(f"  Accuracy Gap         : {(central_accuracy - global_acc_per_round[-1]):.4f}")
print(f"  Hospital A (final)   : {acc_A_final:.4f}")
print(f"  Hospital B (final)   : {acc_B_final:.4f}")
print(f"  Hospital C (final)   : {acc_C_final:.4f}")
print(f"  Communication Rounds : {NUM_ROUNDS}")
print("="*45)